# Generated by Django 4.1.2 on 2022-10-17 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Wrong', regex='^.*em$')], verbose_name='Имя автора')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст автора')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('lit_type', models.CharField(choices=[('a', 'foreign'), ('b', 'domestic'), ('c', 'other')], default='a', max_length=1, verbose_name='Тип литературы')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['id'],
                'unique_together': {('name', 'age')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page_num', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_lib.author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'get_latest_by': 'published',
            },
        ),
    ]
